# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
disable_all_formatting = false
fn_params_layout = "Tall"
force_explicit_abi = true
hard_tabs = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
max_width = 120
merge_derives = false
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 0
tab_spaces = 4
use_field_init_shorthand = false
use_small_heuristics = "Max"
use_try_shorthand = false
